CREATE OR REPLACE NONEDITIONABLE PROCEDURE Create_User(
	NAME VARCHAR2,
	PASSWORD VARCHAR2,
	PHONENUMBER VARCHAR2,
	BIRTHDATE DATE,
	EMAIL VARCHAR2,
	ROLE NUMBER) AS
	USER_ID NUMBER;
	USER_LOGIN NUMBER;
	BEGIN			
		SELECT OBJECT_ID_SEQ.NEXTVAL INTO USER_ID FROM DUAL;
		SELECT USER_LOGIN_SEQ.NEXTVAL INTO USER_LOGIN FROM DUAL;
		INSERT INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME)
			VALUES(USER_ID, NULL, 1, NAME);
		INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
			VALUES(1, USER_ID, USER_LOGIN);
		INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
			VALUES(2, USER_ID, PASSWORD);
		INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
			VALUES(3, USER_ID, NAME);
		INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
			VALUES(4, USER_ID, PHONENUMBER);
		INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, LIST_VALUE_ID)
			VALUES(7, USER_ID, ROLE);
		IF BIRTHDATE IS NOT NULL
			THEN
				INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, DATE_VALUE)
					VALUES(5, USER_ID, BIRTHDATE);
		END IF;
		IF EMAIL IS NOT NULL AND LENGTH(EMAIL) > 0
			THEN
				INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
					VALUES(6, USER_ID, EMAIL);
		END IF;
		COMMIT;
	END;
	
CREATE OR REPLACE NONEDITIONABLE PROCEDURE Create_DoctorSpec(
	TITLE VARCHAR2) AS
	SPEC_ID NUMBER;
	BEGIN			
		SELECT OBJECT_ID_SEQ.NEXTVAL INTO SPEC_ID FROM DUAL;
		INSERT INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME)
			VALUES(SPEC_ID, NULL, 6, TITLE);
		COMMIT;
	END;

CREATE OR REPLACE PROCEDURE EDIT_EMPLOYER_DATA (
    HIRING_DATE VARCHAR2,
    STATUS NUMBER,
    START_WORKING_TIME VARCHAR2,
    END_WORKING_TIME VARCHAR2,
    EMPLOYER_ID NUMBER) AS BEGIN
    UPDATE ATTRIBUTES STATUS SET STATUS.LIST_VALUE_ID = STATUS
        WHERE STATUS.ATTR_ID = 10 AND STATUS.OBJECT_ID = EMPLOYER_ID;
    UPDATE ATTRIBUTES START_WORKING_TIME SET START_WORKING_TIME.VALUE = START_WORKING_TIME
        WHERE START_WORKING_TIME.ATTR_ID = 11 AND START_WORKING_TIME.OBJECT_ID = EMPLOYER_ID;
    UPDATE ATTRIBUTES END_WORKING_TIME SET END_WORKING_TIME.VALUE = END_WORKING_TIME
        WHERE END_WORKING_TIME.ATTR_ID = 12 AND END_WORKING_TIME.OBJECT_ID = EMPLOYER_ID;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE CREATE_EMPLOYER_DATA(
    HIRING_DATE VARCHAR2,
    STATUS NUMBER,
    START_WORKING_TIME VARCHAR2,
    END_WORKING_TIME VARCHAR2,
    EMP_PARENT_ID NUMBER) AS
    EMP_DATA_ID NUMBER;
    BEGIN
        SELECT OBJECT_ID_SEQUENCE.NEXTVAL INTO EMP_DATA_ID FROM DUAL;
        INSERT INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
            VALUES(EMP_DATA_ID, EMP_PARENT_ID, 2, EMP_DATA_ID, NULL);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, DATE_VALUE)
            VALUES (9, EMP_DATA_ID, HIRING_DATE);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, LIST_VALUE_ID)
            VALUES (10, EMP_DATA_ID, STATUS);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE)
            VALUES (11, EMP_DATA_ID, START_WORKING_TIME);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE)
            VALUES (12, EMP_DATA_ID, END_WORKING_TIME);
    COMMIT;
END;

CREATE OR REPLACE NONEDITIONABLE PROCEDURE Create_Work_Day(
 EMPLOYER_ID NUMBER,
 WORK_DATE DATE) AS WORK_DAY_ID NUMBER;
 BEGIN
  SELECT OBJECT_ID_SEQ.NEXTVAL INTO WORK_DAY_ID FROM DUAL;
  INSERT INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME)
   VALUES(WORK_DAY_ID, NULL, 3, WORK_DAY_ID);
  INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE)
   VALUES(14, WORK_DAY_ID, EMPLOYER_ID);
  INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, DATE_VALUE)
   VALUES(15, WORK_DAY_ID, WORK_DATE);
  COMMIT;
 END;

CREATE OR REPLACE PROCEDURE DELETE_WORK_DAY(WORK_DAY_ID NUMBER) AS 
 BEGIN
    DELETE FROM ATTRIBUTES WHERE OBJECT_ID = WORK_DAY_ID;
    DELETE FROM OBJECTS WHERE OBJECT_ID = WORK_DAY_ID;
    COMMIT;
 END;

CREATE OR REPLACE PROCEDURE UPDATE_GENINFO(GEN_OBJECT_ID NUMBER, GEN_ADDRESS VARCHAR2, GEN_PHONE VARCHAR2, GEN_WORKING_START VARCHAR2, GEN_WORKING_END VARCHAR2)
    IS
    BEGIN
        UPDATE ATTRIBUTES ADDRESS SET ADDRESS.VALUE = GEN_ADDRESS
            WHERE ADDRESS.ATTR_ID = 30
            AND ADDRESS.OBJECT_ID = GEN_OBJECT_ID;
        UPDATE ATTRIBUTES PHONE SET PHONE.VALUE = GEN_PHONE
            WHERE PHONE.ATTR_ID = 31
            AND PHONE.OBJECT_ID = GEN_OBJECT_ID;
        UPDATE ATTRIBUTES WORKING_START SET WORKING_START.VALUE = GEN_WORKING_START
            WHERE WORKING_START.ATTR_ID = 32
            AND WORKING_START.OBJECT_ID = GEN_OBJECT_ID;
        UPDATE ATTRIBUTES WORKING_END SET WORKING_END.VALUE = GEN_WORKING_END
            WHERE WORKING_END.ATTR_ID = 33
            AND WORKING_END.OBJECT_ID = GEN_OBJECT_ID;
        COMMIT;
    END;

CREATE OR REPLACE PROCEDURE CREATE_GENINFO (GEN_ADDRESS VARCHAR2, GEN_PHONE VARCHAR2, GEN_WORKING_START VARCHAR2, GEN_WORKING_END VARCHAR2, NAME VARCHAR2)
    IS
    GEN_OBJECT_ID NUMBER;
    BEGIN
        SELECT OBJECT_ID_SEQUENCE.NEXTVAL INTO GEN_OBJECT_ID FROM DUAL;

        INSERT INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
            VALUES (GEN_OBJECT_ID, NULL, 7, NAME, NULL);

        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE)
            VALUES (30, GEN_OBJECT_ID, GEN_ADDRESS);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE)
            VALUES (31, GEN_OBJECT_ID, GEN_PHONE);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE)
            VALUES (32, GEN_OBJECT_ID, GEN_WORKING_START);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE)
            VALUES (33, GEN_OBJECT_ID, GEN_WORKING_END);
        COMMIT;
    END;

CREATE OR REPLACE PROCEDURE CREATE_DOCTORDATA (APPOINTMENT_DURATION VARCHAR2, PARENT NUMBER, SPECIALIZATION NUMBER, NAME VARCHAR2)
    IS
    DOCTORDATA_OBJECT_ID NUMBER;
    BEGIN
        SELECT OBJECT_ID_SEQUENCE.NEXTVAL INTO DOCTORDATA_OBJECT_ID FROM DUAL;

        INSERT INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
            VALUES (DOCTORDATA_OBJECT_ID, PARENT, 4, NAME, NULL);
        INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE)
            VALUES (18, DOCTORDATA_OBJECT_ID, APPOINTMENT_DURATION);
        INSERT INTO OBJREFERENCE (ATTR_ID, REFERENCE, OBJECT_ID)
            VALUES (17, DOCTORDATA_OBJECT_ID, SPECIALIZATION);
        COMMIT;
    END;

create or replace PROCEDURE UPDATE_DOCTORDATA(DOCTORDATA_OBJECT_ID NUMBER, DOCTORDATA_APPOINTMENTDURATION VARCHAR2, SPECIALIZATION NUMBER)
    IS
    BEGIN
        UPDATE ATTRIBUTES SET VALUE = DOCTORDATA_APPOINTMENTDURATION
            WHERE ATTR_ID = 18 AND OBJECT_ID = DOCTORDATA_OBJECT_ID;
        UPDATE OBJREFERENCE SET OBJECT_ID = SPECIALIZATION
            WHERE ATTR_ID = 17 AND REFERENCE = DOCTORDATA_OBJECT_ID;
        COMMIT;
    END;