package com.teama.hospitalsystem.dao;

import com.teama.hospitalsystem.models.DoctorData;
import com.teama.hospitalsystem.util.EAVAttrTypesID;
import com.teama.hospitalsystem.util.EAVObjTypesID;

import java.math.BigInteger;
import java.util.List;

public interface DoctorDataDAO {
    String UPDATE_DOCTORDATA_PROCEDURE = "UPDATE_DOCTORDATA";
    String CREATE_DOCTORDATA_FUNCTION = "CREATE_DOCTORDATA";

    String DOCTORDATA_ID = "DOCTORDATA_ID";
    String APPOINTMENT_DURATION = "APPOINTMENT_DURATION";

    String PARENT_PARAM = "PARENT";
    String SPECIALIZATION_PARAM = "SPECIALIZATION";

    String DOCTORDATA_OBJECT_ID = "DOCTORDATA_OBJECT_ID";
    String DOCTORDATA_APPOINTMENTDURATION = "DOCTORDATA_APPOINTMENTDURATION";

    String SQL_GET_DOCTORDATA_BY_DOCTOR_ID = "SELECT DOCTORDATA.OBJECT_ID DOCTORDATA_ID, " +
            "APPOINTMENTDURATION.VALUE APPOINTMENT_DURATION, " +
            "SPECIALIZATION.OBJECT_ID SECIALIZATION_ID " +
            "FROM OBJECTS DOCTORDATA, ATTRIBUTES APPOINTMENTDURATION, " +
            "OBJREFERENCE SPECIALIZATION " +
            "WHERE DOCTORDATA.PARENT_ID = ? " +
            " AND APPOINTMENTDURATION.ATTR_ID = " + EAVAttrTypesID.APPOINTMENT_DURATION +
            " AND APPOINTMENTDURATION.OBJECT_ID = DOCTORDATA.OBJECT_ID" +
            " AND SPECIALIZATION.ATTR_ID = " + EAVAttrTypesID.SPEC +
            " AND SPECIALIZATION.OBJECT_ID = DOCTORDATA.OBJECT_ID";

    String SQL_GET_DOCTORDATA_ID = "SELECT DOCTORDATA.OBJECT_ID DOCTORDATA_ID, " +
            "APPOINTMENTDURATION.VALUE APPOINTMENT_DURATION, " +
            "SPECIALIZATION.OBJECT_ID SECIALIZATION_ID " +
            "FROM OBJECTS DOCTORDATA, ATTRIBUTES APPOINTMENTDURATION, OBJREFERENCE SPECIALIZATION " +
            "WHERE DOCTORDATA.OBJECT_ID = ? " +
            " AND APPOINTMENTDURATION.ATTR_ID = " + EAVAttrTypesID.APPOINTMENT_DURATION +
            " AND APPOINTMENTDURATION.OBJECT_ID = DOCTORDATA.OBJECT_ID " +
            " AND SPECIALIZATION.ATTR_ID = " + EAVAttrTypesID.SPEC +
            " AND SPECIALIZATION.OBJECT_ID = DOCTORDATA.OBJECT_ID";

    String SQL_GET_DOCTOR_LIST_BY_SPECIALIZATION = "SELECT DISTINCT DOCTORDATA.OBJECT_ID DOCTORDATA_ID, " +
            " APPOINTMENTDURATION.VALUE APPOINTMENT_DURATION, " +
            " SPECIALIZATION.REFERENCE SECIALIZATION_ID" +
            " FROM OBJECTS DOCTORDATA, ATTRIBUTES APPOINTMENTDURATION, " +
            " OBJREFERENCE SPECIALIZATION " +
            " WHERE DOCTORDATA.OBJECT_TYPE_ID = " + EAVObjTypesID.DOCTOR_DATA +
            " AND APPOINTMENTDURATION.ATTR_ID = " + EAVAttrTypesID.APPOINTMENT_DURATION +
            " AND APPOINTMENTDURATION.OBJECT_ID = DOCTORDATA.OBJECT_ID " +
            " AND SPECIALIZATION.ATTR_ID = " + EAVAttrTypesID.SPEC +
            " AND SPECIALIZATION.reference = ?";

    public BigInteger createDoctorData(DoctorData doctorData, BigInteger employerId);
    public void editDoctorData(DoctorData doctorData);
    public DoctorData getDoctorDataByDoctorId(BigInteger id);
    public DoctorData getDoctorDataId(BigInteger id);
    public List<DoctorData> getDoctorListBySpecialization(BigInteger specializationId);
}
