language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  app: hospital-system-app
  api_key:
    secure: F+3Ss0dpYG3pqpAcqpzJrLbe2S39C0xLno3h6zAKjC46twUrbA/jOMwi2+qN1/9WGh4ztRomDwIYd6Cjs++wJ2MwXM4UZO02/wBxPdNNDJn34ryHGN24S/8HEnqbeG2h3KG2SMQ66r5MxnY4EdhXFqlfYaOGDJ+ygdlEZNDHV91A9GzuzN4ldT4pxkaFD0LU/R/2yDHZOWboxE0F0rRF2V66J91xxx5SpJfp7rT5vgo3B1mjGcoiWMuH3t2Yfri1EWbPRRXFSxRNMhjJhFV1bcxvRnX0jvD33rVzuZ28da2644GXKbU5EJIkhGFchstK3SZ68eE89b85KP+A3xxEmbEa9rkdikFLUV72VYfhXMAfLj1yqAD+kbhNfjzXoGrYZF42BgZhEfRdEzuRL1qY/9tI688wTgi3HYrc116S2v8InrrIYud1m+OC/LhbZfx1/x4qiWSMrWWS3X03+Vvo8b7x+vGvNy2UCfBKwyuXGkNnlKsMWea6qVFHdT1m1AuDAjFHf9UtPnlgJXYN1md/YG39w3l1aCr/qLnW8nEWgs25bUIIhJutctQSEss+gKb9nNrpKZ20nPU6sZUaQy6Ldw2xWWN2Xqy3CwLwlUE4jNp5wugEvvFZT6eNykfuRJr3j85sClQxmM95jPFOzZ+4r8iPE03zkKUZsadsy2siOJM=
before_install:
- chmod +x mvnw
