version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku-deploy:
    jobs:
      - heroku/deploy-via-git:
          force: true
          branch: master
          app-name: hospital-system-app
          api-key: HEROKU_API_KEY